version: "3.9"

services:
  src:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: gradeservice
    container_name: "gradeservice"
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
