version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: unless-stopped
    networks:
      - default
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_ROOT_PASSWORD=${MOODLE_DB_PASSWORD}
      - MARIADB_PASSWORD=${MOODLE_DB_PASSWORD}
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:3.11.9
    restart: unless-stopped
    networks:
      - default
      - proxy
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DB_PASSWORD}
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_ROOT_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_SSLPROXY=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.moodle.entrypoints=http"
      - "traefik.http.routers.moodle.rule=Host(`${HOST}`)"
      - "traefik.http.middlewares.moodle-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.moodle.middlewares=moodle-https-redirect"
      - "traefik.http.routers.moodle-secure.entrypoints=https"
      - "traefik.http.routers.moodle-secure.rule=Host(`${HOST}`)"
      - "traefik.http.routers.moodle-secure.tls=true"
      - "traefik.http.routers.moodle-secure.tls.certresolver=http"
      - "traefik.http.routers.moodle-secure.service=moodle"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      - "traefik.http.routers.moodle-secure.middlewares=secHeaders@file"

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local

networks:
  proxy:
    external: true

